version: '3'

services:
  isis3:
    build: .
    image: seignovert/usgs-isis3:3.9.0
    container_name: isis3
    hostname: isis3
    volumes:
      - $PDS_DATA:/usgs/pds
    stdin_open: true
    tty: true
